### ISSUE TITLE
SyntaxError: await is a reserved word 

### ISSUE THREAD

**Issue by mrsufgi** [nrwl/precise-commits#18]
Hey, 
Very nice work on this package! 

I've been trying to integrate precise-commits to our project,
It works pretty good but I guess since you only run the formatter on the changed part of a file you lose async block context. this makes working with async/await files impossible. 

do you thing this is even fixable?

**Comment by JamesHenry** [comment]
Hi @mrsufgi, this should be reported on the prettier repo.

Here is a reproduction of the issue in prettier: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdKXXVAd1VJlwCNUATnQDczAL4gANCAgAHMtHTJQggRHYAFQQiUpUANwikAJlJC8BqMAGs4MAMqyrpKAHNkMAYTjSX6OAIwGpauALaoyPioADb+0gBW6AAeAEKWNnb2qKFwADIucJExcSBOAv4CyOaovJjR0GayAi4wAOomMAAWyAAcAAzSTRD+rZayVU1wFfqF0gJwAI6EpPPBqGERSFGxPiD+oaQeXrvoLq7RcACKhBDwRTvSMDXtxl3IAEyPlqTRZwDCEFC4SqUGgsxAhH8ABUarptiVLG44PYnoEPp8QIjXHAAKJQUxIADMADYxGIgA

**Comment by JamesHenry** [comment]
I have reported it here: https://github.com/prettier/prettier/issues/4822

**Comment by JamesHenry** [comment]
This was fixed in prettier
