### ISSUE TITLE
Doesnt seem to work when requirePragma: true

### ISSUE THREAD

**Issue by omasback** [nrwl/precise-commits#9]
Not sure if this is a bug in your code or prettier. I tried to run prettier cli with a range and it didn't work. So it seems that either this is a bug in prettier or i didnt enter the CLI range options right.

**Comment by JamesHenry** [comment]
Please could you share how you are setting up and running `precise-commits` in this case? (Including any prettier config etc)

**Comment by omasback** [comment]
My package.json: ![image](https://user-images.githubusercontent.com/618294/36277659-5b086c3e-1246-11e8-949f-876f46f43f4b.png)

My .prettierrc: 
![image](https://user-images.githubusercontent.com/618294/36277718-849a8474-1246-11e8-847a-2462c44a857d.png)

How I test: 
1. Save some bad formatting to a file.
2. `git add .`
3. `npm run precise-commits`
4. `--> No formatting changes required in: [file]`
5. change `requirePragma` to false in `.prettierrc`
6. repeat steps 1-3
7. `--> Updated formatting in: [file]`

**Comment by JamesHenry** [comment]
Thanks a lot for providing all the details @omasback!

I can reproduce the issue within `precise-commits`, but more importantly also with just prettier directly. It would appear `rangeStart` and `rangeEnd` cannot easily be combined with `requirePragma` at the moment.

I have reported it in the prettier repo directly here: https://github.com/prettier/prettier/issues/3985

**Comment by omasback** [comment]
Cool, that was my experience as well trying to use prettier CLI with range and pragma combined. Thanks for making that issue!

**Comment by JamesHenry** [comment]
The underlying prettier issue should have now been fixed
